SPRING_APPLICATION_NAME=app

SPRING_DATASOURCE_URL= POSTGRESQL_URL
SPRING_DATASOURCE_USERNAME= POSTGRESQL_USERNAME
SPRING_DATASOURCE_PASSWORD= POSTGRESQL_PASSWORD
SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver

SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
SPRING_JPA_HIBERNATE_DDL_AUTO=update
SPRING_JPA_SHOW_SQL=true
SPRING_DATA_WEB_PAGEABLE_ONE_INDEXED_PARAMETERS=true

SERVER_PORT=8080

CORS_ALLOWED_ORIGINS=http://localhost:3000

SECURITY_JWT_SECRET_KEY=c2VjcmV0S2V5Rm9yVGVzdGluZ1B1cnBvc2VzT25seUZvcklnbmF0aW8=
SECURITY_JWT_EXPIRATION_TIME=86400000
